### ISSUE TITLE
Modality worklist

### ISSUE THREAD

**Issue by mbx2015** [mehmetsen80/EasyPACS#1]
Hello Mehmet,

I'm actually trying to implement your PACS, I want to know If you had implemented the modality worklist or not? if yes How can I query studies with the dcm4che tools ??

Thanks

**Comment by Andrew-wafeeq** [comment]
when i start to run easy.pacs-0.0.1-SNAPSHOT.jar file on cmd, i get the following error:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:199)
at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
at org.easy.Application.main(Application.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.hibernate.validator.internal.engine.ConfigurationImpl.(ConfigurationImpl.java:110)
at org.hibernate.validator.internal.engine.ConfigurationImpl.(ConfigurationImpl.java:86)
at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:381)
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:174)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 28 common frames omitted

2019-06-28 02:07:22.764 INFO 4484 --- [ main] .b.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-thymeleaf-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-web-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-data-jpa-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-logging-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-log4j-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/guava-18.0.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-data-commons-1.10.0.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/org.apache.commons-commons-io-1.3.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jackson-mapper-asl-1.9.13.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jackson-core-asl-1.9.13.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jackson-core-2.5.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-core-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-net-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-tool-dcm2jpg-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-tool-storescu-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-core-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/thymeleaf-spring4-2.1.4.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/thymeleaf-layout-dialect-1.2.7.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-tomcat-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jackson-databind-2.4.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/hibernate-validator-5.1.3.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-web-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-webmvc-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-aop-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-starter-jdbc-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/hibernate-entitymanager-4.3.8.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/javax.transaction-api-1.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-orm-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-data-jpa-1.7.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-aspects-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jcl-over-slf4j-1.7.10.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jul-to-slf4j-1.7.10.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/log4j-over-slf4j-1.7.10.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/logback-classic-1.1.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/slf4j-log4j12-1.7.10.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/log4j-1.2.17.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/slf4j-api-1.7.10.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/commons-io-commons-io-1.3.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-dict-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/junit-4.11.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-conf-core-api-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-imageio-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-imageio-rle-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jai_imageio-1.2-pre-dr-b04.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-tool-common-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-boot-autoconfigure-1.2.2.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/snakeyaml-1.14.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/thymeleaf-2.1.4.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-core-8.0.20.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-el-8.0.20.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-logging-juli-8.0.20.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/tomcat-embed-websocket-8.0.20.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jackson-annotations-2.4.0.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jboss-logging-3.1.3.GA.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/classmate-1.0.0.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-aop-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-context-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-expression-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/aspectjrt-1.8.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/aspectjweaver-1.8.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-jdbc-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/tomcat-jdbc-8.0.20.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-tx-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jboss-logging-annotations-1.2.0.Beta1.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/hibernate-core-4.3.8.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dom4j-1.6.1.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/hibernate-commons-annotations-4.0.5.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/hibernate-jpa-2.1-api-1.0.0.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/javassist-3.18.1-GA.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/logback-core-1.1.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/hamcrest-core-1.3.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/dcm4che-image-3.3.5.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/clibwrapper_jiio-1.2-pre-dr-b04.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/clib_jiio-1.2-pre-dr-b04.zip!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/commons-cli-1.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/tomcat-juli-8.0.20.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/antlr-2.7.7.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/jandex-1.1.0.Final.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/xml-apis-1.0.b2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/ognl-3.0.8.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/unbescape-1.1.0.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/spring-beans-4.1.5.RELEASE.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/commons-logging-1.2.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/aopalliance-1.0.jar!/, jar:file:/C:/EasyPACS/easy.pacs-0.0.1-SNAPSHOT.jar!/lib/mysql-connector-java-5.1.34.jar!/]
2019-06-28 02:07:22.777 ERROR 4484 --- [ main] o.s.boot.SpringApplication : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:199)
at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
at org.easy.Application.main(Application.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.hibernate.validator.internal.engine.ConfigurationImpl.(ConfigurationImpl.java:110)
at org.hibernate.validator.internal.engine.ConfigurationImpl.(ConfigurationImpl.java:86)
at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:381)
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:174)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 28 common frames omitted

java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:199)
at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:615)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
at org.easy.Application.main(Application.java:56)
... 6 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.hibernate.validator.internal.engine.ConfigurationImpl.(ConfigurationImpl.java:110)
at org.hibernate.validator.internal.engine.ConfigurationImpl.(ConfigurationImpl.java:86)
at org.hibernate.validator.HibernateValidator.createGenericConfiguration(HibernateValidator.java:41)
at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:276)
at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:223)
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor$Jsr303ValidatorFactory.run(ConfigurationPropertiesBindingPostProcessor.java:381)
at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.afterPropertiesSet(ConfigurationPropertiesBindingPostProcessor.java:174)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
... 19 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 28 more

can you help me?
